name: terraform-ci
on:
  push:
    branches: [ "main" ]
    paths: [ "**/*.tf", ".github/workflows/terraform-ci.yml" ]
  pull_request:
    paths: [ "**/*.tf", ".github/workflows/terraform-ci.yml" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt check
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        working-directory: ./terraform
        run: terraform init -backend=false
      - name: Terraform validate
        working-directory: ./terraform
        run: terraform validate
